# Generated by Django 5.1.6 on 2026-06-14 15:16

import django.db.models.deletion
import knowledge.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assistant_name', models.CharField(blank=True, default='Assistant', max_length=100)),
                ('company_name', models.CharField(blank=True, default='', max_length=150)),
                ('default_language', models.CharField(blank=True, default='auto', max_length=10)),
                ('tone', models.CharField(choices=[('friendly', 'Friendly'), ('formal', 'Formal'), ('concise', 'Concise')], default='friendly', max_length=20)),
                ('strict_grounding', models.BooleanField(default=True)),
                ('no_answer_message', models.TextField(blank=True, default='')),
                ('top_k', models.PositiveIntegerField(blank=True, null=True)),
                ('similarity_threshold', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=knowledge.models.upload_document_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('source_type', models.CharField(choices=[('file', 'File Upload'), ('api', 'API Sync')], default='file', max_length=10)),
                ('api_url', models.URLField(blank=True, default='', help_text='Source API URL (if synced from API)')),
                ('items_key', models.CharField(blank=True, default='', help_text='JSON key containing items', max_length=100)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.uploadeddocument')),
            ],
            options={
                'ordering': ['document_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('source', models.CharField(choices=[('rag', 'RAG')], default='rag', max_length=16)),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('rating', models.CharField(choices=[('up', 'Helpful'), ('down', 'Not helpful')], max_length=8)),
                ('comment', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating', 'source'], name='knowledge_c_rating_dd65f3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['processing_status', 'is_active'], name='knowledge_u_process_3b1ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'position'], name='knowledge_d_documen_56e966_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'source_id'], name='knowledge_d_documen_7fc863_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'position'), name='unique_chunk_position'),
        ),
    ]
