# Generated by Django 5.1.7 on 2026-06-16 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantQuota',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_documents', models.PositiveIntegerField(blank=True, null=True)),
                ('max_total_mb', models.FloatField(blank=True, null=True)),
                ('max_requests_per_min', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_token_cap', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('chat', 'Chat'), ('embedding', 'Embedding')], default='chat', max_length=16)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('confident', models.BooleanField(default=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='knowledge_u_user_id_a202fd_idx'), models.Index(fields=['user', 'kind', 'created_at'], name='knowledge_u_user_id_ea69df_idx')],
            },
        ),
    ]
