# Generated by Django 5.1.6 on 2026-04-25 15:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedquestion',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixedquestion',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('source', models.CharField(choices=[('qa_bank', 'Q&A bank'), ('rag', 'RAG'), ('fallback', 'Fallback')], default='rag', max_length=16)),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('rating', models.CharField(choices=[('up', 'Helpful'), ('down', 'Not helpful')], max_length=8)),
                ('comment', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating', 'source'], name='knowledge_c_rating_dd65f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=64)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.uploadeddocument')),
            ],
            options={
                'ordering': ['document_id', 'position'],
                'indexes': [models.Index(fields=['document', 'position'], name='knowledge_d_documen_56e966_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'position'), name='unique_chunk_position')],
            },
        ),
    ]
