# Generated by Django 5.1.6 on 2026-05-01 18:02

import knowledge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='api_url',
            field=models.URLField(blank=True, default='', help_text='Source API URL (if synced from API)'),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='items_key',
            field=models.CharField(blank=True, default='', help_text='JSON key containing items', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='source_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('api', 'API Sync')], default='file', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=knowledge.models.upload_document_path),
        ),
    ]
