# Generated by Django 5.1.6 on 2026-06-30 02:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_tenantquota_usagerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnansweredQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('question_key', models.CharField(db_index=True, max_length=500)),
                ('language', models.CharField(blank=True, default='', max_length=8)),
                ('reason', models.TextField(blank=True, default='', help_text='Why the AI kept it.')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('answered', 'Answered'), ('dismissed', 'Dismissed')], default='new', max_length=12)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('last_asked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unanswered_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_asked_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='knowledge_u_user_id_304411_idx'), models.Index(fields=['user', 'last_asked_at'], name='knowledge_u_user_id_f700a0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'question_key'), name='unique_user_question_key')],
            },
        ),
    ]
