# Generated by Django 5.1.6 on 2026-04-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_fixedquestion_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='fixed_question',
        ),
        migrations.RemoveField(
            model_name='unansweredquestion',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='is_fixed',
        ),
        migrations.DeleteModel(
            name='FixedQuestion',
        ),
        migrations.DeleteModel(
            name='UnansweredQuestion',
        ),
    ]
