# Generated by Django 5.1.6 on 2026-08-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_unansweredquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='source_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('api', 'API Sync'), ('website', 'Website Crawl')], default='file', max_length=10),
        ),
    ]
