# Generated by Django 5.1.6 on 2026-06-14 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_documentchunk_content_hash_documentchunk_source_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assistant_name', models.CharField(blank=True, default='Assistant', max_length=100)),
                ('company_name', models.CharField(blank=True, default='', max_length=150)),
                ('default_language', models.CharField(blank=True, default='auto', max_length=10)),
                ('tone', models.CharField(choices=[('friendly', 'Friendly'), ('formal', 'Formal'), ('concise', 'Concise')], default='friendly', max_length=20)),
                ('strict_grounding', models.BooleanField(default=True)),
                ('no_answer_message', models.TextField(blank=True, default='')),
                ('top_k', models.PositiveIntegerField(blank=True, null=True)),
                ('similarity_threshold', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
