# Generated by Django 5.1.6 on 2026-07-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_plan_included_credits_creditwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='allow_api_sync',
            field=models.BooleanField(default=True),
        ),
    ]
