# Generated by Django 5.1.6 on 2026-07-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_plan_allow_api_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaddleWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='paddle_price_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paddle_customer_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paddle_subscription_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
