# Generated by Django 5.1.6 on 2026-07-21 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_paddlewebhookevent_plan_paddle_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditwallet',
            name='last_free_grant_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
