# Generated by Django 5.1.6 on 2026-04-19 20:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('incoming_messages', models.PositiveIntegerField(default=0)),
                ('outgoing_messages', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('api_usage', models.JSONField(default=dict, help_text='Usage count per API endpoint')),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0, help_text='Average response time in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Analytics',
                'verbose_name_plural': 'WhatsApp Analytics',
                'db_table': 'whatsapp_analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='whatsapp_an_date_84a24d_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='WhatsApp phone number without whatsapp: prefix', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(20)])),
                ('profile_name', models.CharField(blank=True, help_text="User's WhatsApp profile name", max_length=255, null=True)),
                ('language_preference', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German')], default='ar', help_text="User's preferred language", max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Timestamp of last message received', null=True)),
                ('message_count', models.PositiveIntegerField(default=0, help_text='Total number of messages exchanged')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional user metadata')),
            ],
            options={
                'verbose_name': 'WhatsApp User',
                'verbose_name_plural': 'WhatsApp Users',
                'db_table': 'whatsapp_users',
                'ordering': ['-last_message_at', '-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='whatsapp_us_phone_n_042a5a_idx'), models.Index(fields=['is_active'], name='whatsapp_us_is_acti_db7feb_idx'), models.Index(fields=['language_preference'], name='whatsapp_us_languag_dc41f1_idx'), models.Index(fields=['last_message_at'], name='whatsapp_us_last_me_07044f_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('rag_chat', 'RAG Chat'), ('simple_chat', 'Simple Chat'), ('ask_questions', 'Ask Questions'), ('ask_una', 'Ask UNA')], default='ask_questions', help_text='Type of chat session', max_length=20)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Store session context like conversation history, current question tree node, etc.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this session expires', null=True)),
                ('message_count', models.PositiveIntegerField(default=0, help_text='Number of messages in this session')),
                ('user', models.ForeignKey(help_text='WhatsApp user this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='WhatsApp.whatsappuser')),
            ],
            options={
                'verbose_name': 'WhatsApp Session',
                'verbose_name_plural': 'WhatsApp Sessions',
                'db_table': 'whatsapp_sessions',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], help_text='Whether this is an incoming or outgoing message', max_length=10)),
                ('message_text', models.TextField(help_text='The actual message content', validators=[django.core.validators.MinLengthValidator(1)])),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='Meta WhatsApp message ID', max_length=100, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', help_text='Delivery status of the message', max_length=20)),
                ('api_endpoint_used', models.CharField(blank=True, help_text='Which chat API was used to generate response', max_length=100, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if message failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional message metadata')),
                ('session', models.ForeignKey(blank=True, help_text='Session this message belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='WhatsApp.whatsappsession')),
                ('user', models.ForeignKey(help_text='WhatsApp user who sent/received this message', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='WhatsApp.whatsappuser')),
            ],
            options={
                'verbose_name': 'WhatsApp Message',
                'verbose_name_plural': 'WhatsApp Messages',
                'db_table': 'whatsapp_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappsession',
            index=models.Index(fields=['user'], name='whatsapp_se_user_id_a62f62_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappsession',
            index=models.Index(fields=['session_type'], name='whatsapp_se_session_fd90ad_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappsession',
            index=models.Index(fields=['is_active'], name='whatsapp_se_is_acti_18fbb2_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappsession',
            index=models.Index(fields=['expires_at'], name='whatsapp_se_expires_f1449b_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['user'], name='whatsapp_me_user_id_c6069d_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['session'], name='whatsapp_me_session_9434e4_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['message_type'], name='whatsapp_me_message_52d0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['status'], name='whatsapp_me_status_63922d_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['created_at'], name='whatsapp_me_created_f7fc48_idx'),
        ),
    ]
