# Generated by Django 5.1.6 on 2026-06-23 23:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number_id', models.CharField(db_index=True, help_text='Meta WhatsApp Business phone-number id that receives messages.', max_length=64, unique=True)),
                ('access_token', models.TextField(blank=True, default='', help_text='Per-number send token; blank falls back to WHATSAPP_ACCESS_TOKEN.')),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(help_text='The tenant whose knowledge answers on this number.', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Account',
                'verbose_name_plural': 'WhatsApp Accounts',
                'db_table': 'whatsapp_accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
