"""Guided question tree with positional multi-language mirroring.

ONE canonical language (``settings.GUIDED_TREE_CANONICAL_LANGUAGE``) is authored
by hand; every other active language is a generated MIRROR of it, matched by
**position** — the node at the same ``order`` under the matching parent — never
by foreign key. Two walks power everything:

* ``position_path(node)``  — the list of ``order`` values from a root down to the
  node (its address in the tree, language-independent).
* ``node_at_path(owner, language, path)`` — walk that address down a given
  language's tree.

From those: ``canonical_of`` (any node → its canonical twin) and ``mirror_of``
(canonical node → its twin in another language).

All edits target the canonical node; mirrors are (re)generated by translation,
in a background thread so writes never block. Rendered trees are cached per
language and invalidated on write.
"""

from __future__ import annotations

import logging
import threading

from django.conf import settings
from django.core.cache import cache
from django.db import transaction

from ..models import AvailableLanguage, QuestionTreeNode

logger = logging.getLogger(__name__)


def canonical_language() -> str:
    return getattr(settings, "GUIDED_TREE_CANONICAL_LANGUAGE", "ar")


def is_canonical(language: str) -> bool:
    return language == canonical_language()


# --------------------------------------------------------------------------- #
# Positional matching
# --------------------------------------------------------------------------- #
def position_path(node: QuestionTreeNode) -> list[int]:
    """The node's address: ``order`` values from the root down to it."""
    path: list[int] = []
    cur = node
    # Follow parents to the root. Bounded by tree depth.
    while cur is not None:
        path.append(cur.order)
        cur = cur.parent
    path.reverse()
    return path


def node_at_path(owner, language: str, path: list[int]) -> QuestionTreeNode | None:
    """Walk ``path`` (a list of orders) down ``language``'s tree for ``owner``."""
    parent = None
    node = None
    for order in path:
        node = QuestionTreeNode.objects.filter(
            owner=owner, language=language, parent=parent, order=order
        ).first()
        if node is None:
            return None
        parent = node
    return node


def canonical_of(node: QuestionTreeNode) -> QuestionTreeNode | None:
    """Return the canonical-language twin of ``node`` (itself if already canonical)."""
    if is_canonical(node.language):
        return node
    return node_at_path(node.owner, canonical_language(), position_path(node))


def mirror_of(canonical_node: QuestionTreeNode, language: str) -> QuestionTreeNode | None:
    """Return the ``language`` twin of a canonical node (None if not generated yet)."""
    if language == canonical_node.language:
        return canonical_node
    return node_at_path(canonical_node.owner, language, position_path(canonical_node))


# --------------------------------------------------------------------------- #
# Ordering (unique among active siblings, per owner + language)
# --------------------------------------------------------------------------- #
def _sibling_qs(owner, language: str, parent):
    return QuestionTreeNode.objects.filter(owner=owner, language=language, parent=parent)


def next_order(owner, language: str, parent) -> int:
    from django.db.models import Max

    current = _sibling_qs(owner, language, parent).aggregate(m=Max("order")).get("m")
    return (current + 1) if current is not None else 0


def order_is_taken(owner, language: str, parent, order: int, exclude_pk=None) -> bool:
    qs = _sibling_qs(owner, language, parent).filter(order=order)
    if exclude_pk is not None:
        qs = qs.exclude(pk=exclude_pk)
    return qs.exists()


# --------------------------------------------------------------------------- #
# Translation
# --------------------------------------------------------------------------- #
def _strip_quotes(text: str) -> str:
    text = text.strip()
    for q in ('"', "'", "«", "»", "“", "”"):
        if len(text) >= 2 and text[0] == q and text[-1] == q:
            text = text[1:-1].strip()
    return text


def translate_text(text: str | None, target_lang: str, *, source_lang: str | None = None) -> str:
    """Translate ``text`` into ``target_lang``. Never raises.

    Empty/blank text is returned as-is. On any LLM failure we try a fallback
    provider, and if that also fails we return the ORIGINAL text (a readable
    degraded state beats a crash or an empty node).
    """
    if not text or not text.strip():
        return text or ""
    src = f" from {source_lang}" if source_lang else ""
    system = (
        "You are a professional translator. Translate the user's text"
        f"{src} into the language with code '{target_lang}'. Preserve meaning, "
        "tone, names, numbers, URLs and formatting. Output ONLY the translation — "
        "no quotes, no notes, no preamble."
    )
    from .llm import get_backend

    for model in (None, "claude-sonnet-5"):  # primary, then a fallback provider
        try:
            out = get_backend(model).complete(system, text)
            out = _strip_quotes(out or "")
            if out:
                return out
        except Exception:
            logger.warning("translate_text: provider %s failed", model or "default", exc_info=True)
            continue
    return text  # last resort: keep the source text rather than lose content


# --------------------------------------------------------------------------- #
# Mirror generation
# --------------------------------------------------------------------------- #
def _upsert_mirror(canonical_node: QuestionTreeNode, language: str, parent_mirror) -> QuestionTreeNode:
    """Create or update the ``language`` mirror of one canonical node."""
    title = translate_text(canonical_node.title, language, source_lang=canonical_node.language)
    answer = translate_text(canonical_node.answer, language, source_lang=canonical_node.language)
    mirror, _created = QuestionTreeNode.objects.update_or_create(
        owner=canonical_node.owner,
        language=language,
        parent=parent_mirror,
        order=canonical_node.order,
        defaults={
            "title": title,
            "answer": answer or None,
            "is_active": canonical_node.is_active,
        },
    )
    return mirror


def translate_subtree(canonical_node: QuestionTreeNode, language: str, parent_mirror=None) -> None:
    """(Re)generate the ``language`` mirror of ``canonical_node`` and its subtree.

    Failures are isolated per child, so one bad node can't abort the whole branch.
    """
    mirror = _upsert_mirror(canonical_node, language, parent_mirror)
    for child in canonical_node.children.all().order_by("order", "created_at"):
        try:
            translate_subtree(child, language, parent_mirror=mirror)
        except Exception:
            logger.exception("translate_subtree: child %s failed", child.pk)


def active_target_languages() -> list[str]:
    """Active languages that are NOT the canonical one (the mirror targets)."""
    canon = canonical_language()
    return list(
        AvailableLanguage.objects.filter(is_active=True)
        .exclude(code=canon)
        .values_list("code", flat=True)
    )


def resync_language(owner, language: str) -> None:
    """Wipe and rebuild an entire language's tree from the canonical tree.

    Used when adding a brand-new language, or to repair drift.
    """
    if is_canonical(language):
        return
    with transaction.atomic():
        QuestionTreeNode.objects.filter(owner=owner, language=language).delete()
    roots = QuestionTreeNode.objects.filter(
        owner=owner, language=canonical_language(), parent__isnull=True
    ).order_by("order", "created_at")
    for root in roots:
        try:
            translate_subtree(root, language)
        except Exception:
            logger.exception("resync_language: root %s failed", root.pk)
    invalidate_cache(owner, [language])


# --------------------------------------------------------------------------- #
# Async dispatch
# --------------------------------------------------------------------------- #
def _run_bg(fn, *args) -> None:
    from django.db import connection

    try:
        fn(*args)
    except Exception:
        logger.exception("guided_tree background task failed")
    finally:
        connection.close()


def _dispatch(fn, *args) -> None:
    """Run ``fn`` in a thread unless GUIDED_TREE_TRANSLATE_MODE is 'sync'."""
    mode = getattr(settings, "GUIDED_TREE_TRANSLATE_MODE", "thread")
    if mode == "sync":
        fn(*args)
        return
    threading.Thread(target=_run_bg, args=(fn, *args), daemon=True).start()


def _regen_node_mirrors(owner_id, canonical_pk) -> None:
    """Re-translate one canonical node's subtree into every active target language."""
    node = QuestionTreeNode.objects.filter(pk=canonical_pk).first()
    if node is None:
        return
    for language in active_target_languages():
        try:
            translate_subtree(node, language, parent_mirror=_parent_mirror_for(node, language))
        except Exception:
            logger.exception("regen mirrors: node %s lang %s failed", canonical_pk, language)
    invalidate_cache(node.owner, active_target_languages())


def _parent_mirror_for(canonical_node: QuestionTreeNode, language: str):
    """The mirror of this node's PARENT in ``language`` (None for a root)."""
    if canonical_node.parent_id is None:
        return None
    return mirror_of(canonical_node.parent, language)


# --------------------------------------------------------------------------- #
# CRUD (always targets canonical; mirrors follow asynchronously)
# --------------------------------------------------------------------------- #
def create_node(*, owner, parent=None, title, answer=None, order=None, is_active=True) -> QuestionTreeNode:
    """Create a canonical node; generate mirrors in the background."""
    canon = canonical_language()
    parent_canonical = canonical_of(parent) if parent is not None else None
    if order is None:
        order = next_order(owner, canon, parent_canonical)
    elif order_is_taken(owner, canon, parent_canonical, order):
        raise ValueError("A sibling already uses that order (must be unique among siblings).")
    node = QuestionTreeNode.objects.create(
        owner=owner,
        parent=parent_canonical,
        title=title,
        answer=answer or None,
        order=order,
        is_active=is_active,
        language=canon,
    )
    invalidate_cache(owner, [canon])
    _dispatch(_regen_node_mirrors, owner.pk, node.pk)
    return node


def update_node(node: QuestionTreeNode, *, title=None, answer=None, order=None, is_active=None) -> QuestionTreeNode:
    """Edit a node (resolved to canonical); re-translate its subtree in the background."""
    canonical = canonical_of(node)
    if canonical is None:
        raise ValueError("Could not resolve this node to its canonical version.")
    canon = canonical_language()
    if order is not None and order != canonical.order:
        if order_is_taken(owner=canonical.owner, language=canon, parent=canonical.parent, order=order, exclude_pk=canonical.pk):
            raise ValueError("A sibling already uses that order (must be unique among siblings).")
    fields = []
    if title is not None:
        canonical.title = title; fields.append("title")
    if answer is not None:
        canonical.answer = answer or None; fields.append("answer")
    if order is not None:
        canonical.order = order; fields.append("order")
    if is_active is not None:
        canonical.is_active = is_active; fields.append("is_active")
    if fields:
        canonical.save(update_fields=fields + ["updated_at"])
    invalidate_cache(canonical.owner, [canon])
    # An order change moves the node's ADDRESS, so old mirrors are stale → resync
    # the affected languages entirely; otherwise just re-translate this subtree.
    if "order" in fields:
        for language in active_target_languages():
            _dispatch(resync_language, canonical.owner, language)
    else:
        _dispatch(_regen_node_mirrors, canonical.owner.pk, canonical.pk)
    return canonical


def delete_node(node: QuestionTreeNode) -> None:
    """Delete a node: resolve to canonical → drop every language mirror → drop canonical."""
    canonical = canonical_of(node)
    if canonical is None:
        node.delete()
        return
    owner = canonical.owner
    languages = active_target_languages()
    for language in languages:
        mirror = mirror_of(canonical, language)
        if mirror is not None:
            mirror.delete()  # cascades its own subtree
    canonical.delete()  # cascades canonical subtree
    invalidate_cache(owner, [canonical_language(), *languages])


# --------------------------------------------------------------------------- #
# Cached reads
# --------------------------------------------------------------------------- #
def _cache_key(owner_id, language: str) -> str:
    return f"guided_tree:{owner_id}:{language}"


def invalidate_cache(owner, languages) -> None:
    owner_id = getattr(owner, "pk", owner)
    cache.delete_many([_cache_key(owner_id, lang) for lang in languages])


def _serialize(node: QuestionTreeNode, by_parent: dict) -> dict:
    return {
        "id": str(node.id),
        "title": node.title,
        "answer": node.answer,
        "order": node.order,
        "language": node.language,
        "children": [
            _serialize(child, by_parent)
            for child in sorted(
                by_parent.get(node.id, []), key=lambda n: (n.order, n.created_at)
            )
        ],
    }


def build_tree(owner, language: str) -> list[dict]:
    """Full nested tree for one language — ONE query, grouped in memory (no N+1)."""
    nodes = list(
        QuestionTreeNode.objects.filter(owner=owner, language=language, is_active=True)
    )
    by_parent: dict = {}
    for n in nodes:
        by_parent.setdefault(n.parent_id, []).append(n)
    roots = sorted(by_parent.get(None, []), key=lambda n: (n.order, n.created_at))
    return [_serialize(r, by_parent) for r in roots]


def get_tree(owner, language: str) -> list[dict]:
    """Cached nested tree for ``language`` (TTL = GUIDED_TREE_CACHE_TTL)."""
    ttl = int(getattr(settings, "GUIDED_TREE_CACHE_TTL", 300))
    if ttl <= 0:
        return build_tree(owner, language)
    key = _cache_key(owner.pk, language)
    cached = cache.get(key)
    if cached is not None:
        return cached
    tree = build_tree(owner, language)
    cache.set(key, tree, ttl)
    return tree
